### ISSUE TITLE
ModuleNotFoundError: No module named 'gitdb.utils.compat'

### ISSUE THREAD

**Issue by patsevanton** [TinkoffCreditSystems/Nginx-builder#25]
Hello! Try use Nginx-builder.

Version
```
cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)
```

Install and run
```
yum install -y epel-release rpmdevtools mc git 
yum install -y gcc make automake yum-utils redhat-lsb-core openssl-devel zlib-devel pcre-devel epel-release
yum install -y python36 python36-devel python36-pip
git  clone https://github.com/TinkoffCreditSystems/Nginx-builder.git
cd Nginx-builder/
pip3.6 install -r requirements.txt --no-cache-dir
./main.py build -f example.config.yaml -r 1
```

Error:
```
./main.py build -f example.config.yaml 
Traceback (most recent call last):
  File "./main.py", line 6, in <module>
    from src import downloader
  File "/root/Nginx-builder/src/downloader.py", line 5, in <module>
    import git
  File "/usr/local/lib/python3.6/site-packages/git/__init__.py", line 38, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "/usr/local/lib/python3.6/site-packages/git/exc.py", line 9, in <module>
    from git.compat import UnicodeMixin, safe_decode, string_types
  File "/usr/local/lib/python3.6/site-packages/git/compat.py", line 16, in <module>
    from gitdb.utils.compat import (
ModuleNotFoundError: No module named 'gitdb.utils.compat'
```

**Comment by therb1** [comment]
Fix in PR https://github.com/TinkoffCreditSystems/Nginx-builder/pull/28
